# Generated by Django 5.1.4 on 2024-12-31 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undefined', max_length=200)),
                ('url', models.ImageField(upload_to='uploads/images/')),
                ('supplier_name', models.CharField(max_length=50)),
                ('width', models.CharField(default='undefined', max_length=10)),
                ('height', models.CharField(default='undefined', max_length=10)),
                ('image_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images_management_service.imageimport')),
            ],
        ),
    ]
