# Generated by Django 5.1.4 on 2024-12-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_management_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageimport',
            name='status',
            field=models.CharField(default='Non démarré', max_length=50),
        ),
    ]
